'''
This file is used for negative sample generation.
Negative samples are responses generated by our model based on first 3 lines,
and the gold examples will be the ones by Shakespeare.
Run:
python generate_negative_samples.py --use_gpu
'''

import os
import argparse
import torch

from tqdm import tqdm

from datasets import HeldOutSonnetsDataset
from sonnet_generation import SonnetGPT


@torch.no_grad()
def generate_negative_samples(args):
  device = torch.device('cuda') if args.use_gpu else torch.device('cpu')  
  saved = torch.load(args.save_path, weights_only=False)
  model = SonnetGPT(saved['args'])
  model.load_state_dict(saved['model'], strict=False if args.use_lora else True)
  model = model.to(device)
  model.eval()

  # Create the held-out dataset: these only have the first 3 lines
  held_out_sonnet_dataset = HeldOutSonnetsDataset(args.sonnet_path)
  
  os.makedirs(os.path.dirname(args.sonnet_out), exist_ok=True)
  with open(args.sonnet_out, "w") as f:
    f.write(f"---Generated Sonnets--- \n\n")

  for item in held_out_sonnet_dataset:
    sonnet_id = item[0]
    prompt = '\n'.join(item[1])
    encoding = model.tokenizer(prompt, return_tensors='pt', padding=False, truncation=True).to(device)
    output = model.generate(encoding['input_ids'], temperature=args.temperature, top_p=args.top_p)[0][0]
    decoded_output = model.tokenizer.decode(output)
    full_sonnet = f'{decoded_output}\n\n'
    generated_sonnets = [sonnet_id, full_sonnet]

    # print(f'{decoded_output}\n\n')
  
    with open(args.sonnet_out, "a") as f:
      f.write(f"\n{generated_sonnets[0]+1}\n")
      f.write(generated_sonnets[1])


def get_args():
  parser = argparse.ArgumentParser()

  parser.add_argument("--sonnet_path", type=str, default="data/sonnets.txt")
  parser.add_argument("--sonnet_out", type=str, default="predictions/negative_sonnets.txt")
  parser.add_argument("--save_path", type=str, default="checkpoints/best_sonnet.pt")

  parser.add_argument("--use_gpu", action='store_true')

  # Generation parameters.
  parser.add_argument("--temperature", type=float, help="softmax temperature.", default=1.2)
  parser.add_argument("--top_p", type=float, help="Cumulative probability distribution for nucleus sampling.",
                      default=0.9)

  parser.add_argument("--use_lora", action='store_true', default=False)
  parser.add_argument("--r", help='r for LoRA', type=int, default=8)
  parser.add_argument("--alpha", type=float, 
                      help='alpha for LoRA, recommend to initialize α/r = 1 and finetune r', default=8)

  args = parser.parse_args()
  return args


if __name__ == '__main__':
  args = get_args()
  if args.use_lora:
    args.save_path = args.save_path.replace('.pt', f'-lora-r{args.r}.pt')  # load path.
  generate_negative_samples(args)